version: '3'

services: 
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: wishlist 
      POSTGRES_PASSWORD: wishlist
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    volumes: 
      - ./tmp/db:/var/lib/redis/data
    ports:
      - "6379:6379"

  api:
    build: 
      dockerfile: ./docker/rails.dockerfile
      context: .
    container_name: api
    image: lucas/api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - ./:/var/www/api
    ports: 
      - "3000:3000"
    env_file:
      - .env
    depends_on: 
      - db
      - redis

  sidekiq:
    build: 
      dockerfile: ./docker/rails.dockerfile
      context: .
    container_name: sidekiq
    image: lucas/sidekiq
    command: bundle exec sidekiq
    volumes: 
      - ./:/var/www/api
      - /var/www/api/tmp/
    env_file:
      - .env
    depends_on: 
      - db
      - redis
      - api